### ISSUE TITLE
MapStore Support

### ISSUE THREAD

**Issue by luissantos** [tolitius/chazel#8]
Hi,

1st of all I would like to say thank you for the great work. 

Do you have any plans to implement a simple MapStore implementation
that would allow any storage backend to be plugged into HazelCast? 

I would love to contribute to such a feature if required.

**Comment by tolitius** [comment]
great idea about [MapStore](https://docs.hazelcast.org/docs/4.0.2/javadoc/com/hazelcast/map/MapStore.html)

I saw your question and upgraded chazel to support Hazelcast 4.0+ so you can add this feature on top of the new version, since there were many API breakages from Hazelcast `3.x.x` to `4.0+`

but yea, pull request is quite welcome: it is probably best to create a separate namespace i.e. `chazel.store` for it to make things more concise.

**Comment by luissantos** [comment]
Great. I will work on a PoC and open a PR asap.
